spring:
    application:
        name: liteflow-nacos

liteflow:
    rule-source-ext-data-map:
        serverAddr: 182.254.246.42:8848
        dataId: demo_rule
        group: DEFAULT_GROUP
        namespace: e516e1e7-7c15-4d24-83c3-e2d29e5f9172
        username: nacos
        password: nacos